### PR TITLE
Add jQuery 3 support.

### PR DESCRIPTION
**Pull request by CUnknown**
In combination with https://github.com/rails/jquery-rails/pull/220

### CODE REVIEW

**Comment by kenn** [comment]
Awesome, thanks!

**Comment by kenn** [comment]
Ah, it hasn't been merged in the upstream yet? I'm going to have to revert until it's accepted then...

**Comment by scambra** [comment]
jquery-rails already provides jquery3, could you merge again?

**Comment by kenn** [comment]
If you could make a pull request with a tested code, I'd appreciate it!

**Pull request merged**
